export const songs = ["Alma Mia",
"Amar y vivir",
"Amor Incomparable",
"Amor sin esperanza",
"Arrepentida",
"Aunque me duela el alma",
"Ayer y Hoy",
"Azabache",
"Canta pajarito canta",
"Carcel de amor",
"Carnaval de la Vida",
"Cinco centavitos",
"Cuando Llora Mi Guitarra",
"De Cigarro en Cigarro",
"Devuelveme el corazon",
"El aguacate",
"El principe",
"Fatalidad",
"Hablame",
"Historia de Amor",
"Interrogacion",
"Los versos para mi madre",
"Naufrago de Amor",
"Niegalo todo",
"No Me Toquen Ese Vals",
"No voy a vengarme",
"Nuestro Juramento",
"Odiame",
"Para que se quiere",
"Pasional",
"Que dios me libre",
"Que nadie sepa mi sufrir",
"Reminiscencias",
"Rondando Tu Esquina",
"Sendas Distintas",
"Senderito de amor",
"Te esperare",
"Te odio y te quiero",
"Tu Culpa",
"Tu duda y la mia",
"Tu vanidad",
"Un disco mas"];
